### ISSUE TITLE
database_api exited with code 1

### ISSUE THREAD

**Issue by Mati018** [gaganmanku96/Finding-missing-person-using-AI#15]
```
database_api     | "database_pg"
database_api     | Traceback (most recent call last):
database_api     |   File "/usr/local/bin/uvicorn", line 8, in <module>
database_api     |     sys.exit(main())
database_api     |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
database_api     |     return self.main(*args, **kwargs)
database_api     |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
database_api     |     rv = self.invoke(ctx)
database_api     |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
database_api     |     return ctx.invoke(self.callback, **ctx.params)
database_api     |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
database_api     |     return callback(*args, **kwargs)
database_api     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 357, in main
database_api     |     run(**kwargs)
database_api     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 381, in run
database_api     |     server.run()
database_api     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/_impl/asyncio.py", line 47, in run
database_api     |     loop.run_until_complete(self.serve(sockets=sockets))
database_api     |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
database_api     |     return future.result()
database_api     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/_impl/asyncio.py", line 54, in serve
database_api     |     config.load()
database_api     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 306, in load
database_api     |     self.loaded_app = import_from_string(self.app)
database_api     |   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
database_api     |     module = importlib.import_module(module_str)
database_api     |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
database_api     |     return _bootstrap._gcd_import(name[level:], package, level)
database_api     |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
database_api     |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
database_api     |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
database_api     |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
database_api     |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
database_api     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
database_api     |   File "./main.py", line 12, in <module>
database_api     |     create()
database_api     |   File "./create_tables.py", line 10, in create
database_api     |     with PostgresConnection() as conn:
database_api     |   File "./postgres.py", line 32, in __enter__
database_api     |     raise e
database_api     |   File "./postgres.py", line 22, in __enter__
database_api     |     self.connection = psycopg2.connect(
database_api     |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
database_api     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
database_api     | psycopg2.OperationalError: could not translate host name ""database_pg"" to address: Name or service not known
database_api     | 
database_api exited with code 1

```

**Comment by gaganmanku96** [comment]
@Mati018 Can you also mention the OS you are using along with the steps you took to run it?

**Comment by Mati018** [comment]
OS - Kalil Linux
I face this while installing with docker, when i hit `$ docker-compose up --build` i got `database_api exited with code 1`

And when i try to install without docker i got these after `$ uvicorn main:app --port 8002`
`Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 362, in main
    run(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 55, in serve
    config.load()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 6, in <module>
    from db_api import (authenticate_user, submit_case, get_train_data,
  File "./db_api.py", line 3, in <module>
    from postgres import PostgresConnection
  File "./postgres.py", line 8, in <module>
    class PostgresConfig():
  File "./postgres.py", line 9, in PostgresConfig
    PG_DATABASE = os.environ['PG_DATABASE']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'PG_DATABASE'`

**Comment by gaganmanku96** [comment]
@Mati018 
I updated the env file in config. Can you try re-running it with the latest changes (using docker-compose up --build)?
